# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'TreeTableView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TreeTableView

  target 'TreeTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Masonry', '~> 1.0.2'
pod 'YYKit', '~> 1.0.9'
end
